development:
  encoding: utf8
  database: ${artifactId}_development
  pool: 5
  username: root
  host: localhost
  port: 3306

staging:
  encoding: utf8
  database: ${artifactId}_staging
  pool: 5
  username: root
  host: localhost
  port: 3306

test:
  encoding: utf8
  database: ${artifactId}_test
  pool: 5
  username: root
  host: localhost
  port: 3306

production:
  encoding: utf8
  database: ${artifactId}_production
  pool: 5
  username: root
  host: localhost
  port: 3306

