development:
  encoding: utf8
  database: exampl_data_development
  pool: 5
  username: root
  host: localhost
  port: 3306

staging:
  encoding: utf8
  database: example_data_staging
  pool: 5
  username: root
  host: localhost
  port: 3306

test:
  encoding: utf8
  database: example_data_test
  pool: 5
  username: root
  host: localhost
  port: 3306

production:
  encoding: utf8
  database: example_data_production
  pool: 5
  username: root
  host: localhost
  port: 3306

