set(CPACK_GENERATOR "DEB")
set(CPACK_DEBIAN_PACKAGE_NAME "work")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "i386")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Tommy Chheng")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Sample DEB packaging from CMake")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")

# Scripts for pre or post installation
#set( CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/CMake/debian/postinst;${CMAKE_CURRENT_SOURCE_DIR}/CMake/debian/prerm;" )
